In [1]:
import numpy as np
import pandas as pd
from quantfreedom.testing import testing_combine_evals
from quantfreedom.evaluators import eval_is_below
from quantfreedom.indicators.talib_ind import from_talib
from itertools import product
prices = pd.read_hdf('../tests/data/prices.hd5')

In [2]:
rsi_ind = from_talib(
    func_name='rsi',
    prices=prices,
    cart_product=False,
    combos=False,
    timeperiod=[15, 30],
)
ema_ind = from_talib(
    func_name='ema',
    prices=prices,
    cart_product=False,
    combos=False,
    timeperiod=[100, 200, 300],
)
rsi_ema_ind = from_talib(
    func_name='ema',
    indicator_data=rsi_ind,
    cart_product=False,
    combos=False,
    timeperiod=[100, 200, 300],
)

In [3]:
ema_is_below = eval_is_below(
    want_to_evaluate=ema_ind,
    prices=prices,
    cand_ohlc='close'
)
rsi_is_below = eval_is_below(
    want_to_evaluate=rsi_ind,
    user_args=[50,60],
)
rsi_ema_is_below = eval_is_below(
    want_to_evaluate=rsi_ema_ind,
    indicator_data=rsi_ind,
)

In [5]:
testing_combine_evals(
    bigger_df=rsi_is_below,
    smaller_df=rsi_ema_is_below,
)['BTCUSDT']

RSI_timeperiod          15                                        30         \
RSI_is_below            50                   60                   50
RSI_EMA_timeperiod     100    200    300    100    200    300    100    200
EMA_is_below           RSI    RSI    RSI    RSI    RSI    RSI    RSI    RSI
open_time
2022-04-01 00:00:00  False  False  False  False  False  False  False  False
2022-04-01 00:30:00  False  False  False  False  False  False  False  False
2022-04-01 01:00:00  False  False  False  False  False  False  False  False
2022-04-01 01:30:00  False  False  False  False  False  False  False  False
2022-04-01 02:00:00  False  False  False  False  False  False  False  False
...                    ...    ...    ...    ...    ...    ...    ...    ...
2023-01-02 22:00:00  False  False  False  False   True   True  False  False
2023-01-02 22:30:00  False  False  False  False  False  False  False  False
2023-01-02 23:00:00  False  False  False  False  False  False  False  False
2023-01-02 23:30:00  False  False  False  False  False  False  False  False
2023-01-03 00:00:00  False  False  False  False  False  False  False  False

RSI_timeperiod
RSI_is_below                   60
RSI_EMA_timeperiod     300    100    200    300
EMA_is_below           RSI    RSI    RSI    RSI
open_time
2022-04-01 00:00:00  False  False  False  False
2022-04-01 00:30:00  False  False  False  False
2022-04-01 01:00:00  False  False  False  False
2022-04-01 01:30:00  False  False  False  False
2022-04-01 02:00:00  False  False  False  False
...                    ...    ...    ...    ...
2023-01-02 22:00:00  False   True   True   True
2023-01-02 22:30:00  False  False  False   True
2023-01-02 23:00:00  False  False   True   True
2023-01-02 23:30:00  False  False  False  False
2023-01-03 00:00:00  False  False  False  False

[13296 rows x 12 columns]

In [7]:
testing_combine_evals(
    bigger_df=ema_is_below,
    smaller_df=rsi_is_below,
)['BTCUSDT']

EMA_timeperiod         100                         200                       \
EMA_is_below         close                       close
RSI_timeperiod          15            30            15            30
RSI_is_below            50     60     50     60     50     60     50     60
open_time
2022-04-01 00:00:00  False  False  False  False  False  False  False  False
2022-04-01 00:30:00  False  False  False  False  False  False  False  False
2022-04-01 01:00:00  False  False  False  False  False  False  False  False
2022-04-01 01:30:00  False  False  False  False  False  False  False  False
2022-04-01 02:00:00  False  False  False  False  False  False  False  False
...                    ...    ...    ...    ...    ...    ...    ...    ...
2023-01-02 22:00:00  False   True  False   True  False   True  False   True
2023-01-02 22:30:00   True   True  False   True   True   True  False   True
2023-01-02 23:00:00  False   True  False   True  False   True  False   True
2023-01-02 23:30:00   True   True   True   True   True   True   True   True
2023-01-03 00:00:00   True   True  False   True   True   True  False   True

EMA_timeperiod         300
EMA_is_below         close
RSI_timeperiod          15            30
RSI_is_below            50     60     50     60
open_time
2022-04-01 00:00:00  False  False  False  False
2022-04-01 00:30:00  False  False  False  False
2022-04-01 01:00:00  False  False  False  False
2022-04-01 01:30:00  False  False  False  False
2022-04-01 02:00:00  False  False  False  False
...                    ...    ...    ...    ...
2023-01-02 22:00:00  False   True  False   True
2023-01-02 22:30:00   True   True  False   True
2023-01-02 23:00:00  False   True  False   True
2023-01-02 23:30:00   True   True   True   True
2023-01-03 00:00:00   True   True  False   True

[13296 rows x 12 columns]